
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD AND CADENA COMA COMIILLATS COMILLAD COMILLAS COMILLATD DECREMENTO DIVIDE DIVIDE_E DOSPTO DOUBLE EQUALS FALSE FOR ID INCREMENTO INT LCORCHETE LCURLYB LISTA LPAREN MAPA MAYORQUE MENORQUE MINUS NEW NOT NUMBER OR PLUS PRINT PTO PUNTCOM PUT RCORCHETE RCURLYB RPAREN SUBSTRING TIMES TRUE UPDATE VAR VARBOOL VARDOUBLE WHILEexpresion : lista\n    | mapa\n    | variable\n    | concatenacion\n    | incremento\n    | decremento\n    variable : VAR ID EQUALS expresionVar PUNTCOM\n                | VAR ID PUNTCOM\n                | expresionBoolvalorVar : NUMBER\n                | DOUBLE\n                | CADENAexpresionVar : valorVar\n                    | ID \n                    | expresionVar operadorA expresionVarexpresionBool : VARBOOL ID EQUALS booleano pto_coma\n                     | VAR ID EQUALS booleano pto_comabooleano : TRUE\n    | FALSElista : expLista\n    | add_lista\n    expLista : VAR ID EQUALS NEW LISTA LPAREN NUMBER RPAREN pto_coma\n        | VAR ID EQUALS NEW LISTA LPAREN RPAREN pto_coma\n        | VAR ID EQUALS LCORCHETE elementosLista RCORCHETE pto_coma\n        add_lista : ID LCORCHETE NUMBER RCORCHETE EQUALS num_cadena pto_coma\n    | ID PTO ADD LPAREN num_cadena RPAREN pto_coma\n    num_cadena : NUMBER\n    | CADENAelementosLista : CADENA\n        | NUMBER\n        | CADENA COMA elementosLista\n        | NUMBER COMA elementosLista\n        |\n    mapa : expMapa\n    | add_mapa\n    expMapa : VAR ID EQUALS NEW MAPA LPAREN RPAREN pto_coma\n    | MAPA ID EQUALS LCURLYB elementosMapa RCURLYB pto_coma\n    elementosMapa : num_cadena DOSPTO num_cadena\n    | num_cadena DOSPTO num_cadena COMA elementosMapa\n    add_mapa : ID LCORCHETE CADENA RCORCHETE EQUALS CADENA pto_coma\n    operadorA : PLUS\n    | MINUS\n    | TIMES\n    | DIVIDE\n    | DIVIDE_E\n    incremento : ID INCREMENTO pto_comadecremento : ID DECREMENTO pto_comaconcatenacion : VAR ID EQUALS ID PTO SUBSTRING LPAREN NUMBER COMA NUMBER RPAREN pto_coma\n    pto_coma : PUNTCOM'
    
_lr_action_items = {'VAR':([0,],[12,]),'ID':([0,12,15,16,24,52,53,54,55,56,57,],[13,17,22,23,34,74,-41,-42,-43,-44,-45,]),'MAPA':([0,37,],[15,59,]),'VARBOOL':([0,],[16,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,14,25,26,27,28,51,63,71,89,92,93,94,95,99,100,103,107,],[0,-1,-2,-3,-4,-5,-6,-20,-21,-34,-35,-9,-8,-46,-49,-47,-7,-17,-16,-24,-25,-40,-26,-37,-23,-36,-22,-48,]),'INCREMENTO':([13,],[18,]),'DECREMENTO':([13,],[19,]),'LCORCHETE':([13,24,],[20,38,]),'PTO':([13,34,],[21,50,]),'EQUALS':([17,22,23,45,46,],[24,32,33,64,65,]),'PUNTCOM':([17,18,19,34,35,36,39,40,41,42,43,44,49,67,68,73,74,77,80,81,82,83,87,88,98,106,],[25,27,27,-14,51,-10,27,-13,-18,-19,-11,-12,27,-27,-28,-15,-14,27,27,27,27,27,27,27,27,27,]),'NUMBER':([20,24,38,47,48,52,53,54,55,56,57,64,75,78,79,84,85,101,102,],[29,36,62,67,67,36,-41,-42,-43,-44,-45,67,86,62,62,67,97,67,105,]),'CADENA':([20,24,38,47,48,52,53,54,55,56,57,64,65,78,79,84,101,],[30,44,61,68,68,44,-41,-42,-43,-44,-45,68,81,61,61,68,68,]),'ADD':([21,],[31,]),'NEW':([24,],[37,]),'TRUE':([24,33,],[41,41,]),'FALSE':([24,33,],[42,42,]),'DOUBLE':([24,52,53,54,55,56,57,],[43,43,-41,-42,-43,-44,-45,]),'RCORCHETE':([29,30,38,60,61,62,78,79,90,91,],[45,46,-33,77,-29,-30,-33,-33,-31,-32,]),'LPAREN':([31,58,59,72,],[47,75,76,85,]),'LCURLYB':([32,],[48,]),'PLUS':([34,35,36,40,43,44,73,74,],[-14,53,-10,-13,-11,-12,53,-14,]),'MINUS':([34,35,36,40,43,44,73,74,],[-14,54,-10,-13,-11,-12,54,-14,]),'TIMES':([34,35,36,40,43,44,73,74,],[-14,55,-10,-13,-11,-12,55,-14,]),'DIVIDE':([34,35,36,40,43,44,73,74,],[-14,56,-10,-13,-11,-12,56,-14,]),'DIVIDE_E':([34,35,36,40,43,44,73,74,],[-14,57,-10,-13,-11,-12,57,-14,]),'LISTA':([37,],[58,]),'SUBSTRING':([50,],[72,]),'COMA':([61,62,67,68,96,97,],[78,79,-27,-28,101,102,]),'RPAREN':([66,67,68,75,76,86,105,],[82,-27,-28,87,88,98,106,]),'DOSPTO':([67,68,70,],[-27,-28,84,]),'RCURLYB':([67,68,69,96,104,],[-27,-28,83,-38,-39,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'lista':([0,],[2,]),'mapa':([0,],[3,]),'variable':([0,],[4,]),'concatenacion':([0,],[5,]),'incremento':([0,],[6,]),'decremento':([0,],[7,]),'expLista':([0,],[8,]),'add_lista':([0,],[9,]),'expMapa':([0,],[10,]),'add_mapa':([0,],[11,]),'expresionBool':([0,],[14,]),'pto_coma':([18,19,39,49,77,80,81,82,83,87,88,98,106,],[26,28,63,71,89,92,93,94,95,99,100,103,107,]),'expresionVar':([24,52,],[35,73,]),'booleano':([24,33,],[39,49,]),'valorVar':([24,52,],[40,40,]),'operadorA':([35,73,],[52,52,]),'elementosLista':([38,78,79,],[60,90,91,]),'num_cadena':([47,48,64,84,101,],[66,70,80,96,70,]),'elementosMapa':([48,101,],[69,104,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> lista','expresion',1,'p_expresion','parser.py',5),
  ('expresion -> mapa','expresion',1,'p_expresion','parser.py',6),
  ('expresion -> variable','expresion',1,'p_expresion','parser.py',7),
  ('expresion -> concatenacion','expresion',1,'p_expresion','parser.py',8),
  ('expresion -> incremento','expresion',1,'p_expresion','parser.py',9),
  ('expresion -> decremento','expresion',1,'p_expresion','parser.py',10),
  ('variable -> VAR ID EQUALS expresionVar PUNTCOM','variable',5,'p_variable','parser.py',15),
  ('variable -> VAR ID PUNTCOM','variable',3,'p_variable','parser.py',16),
  ('variable -> expresionBool','variable',1,'p_variable','parser.py',17),
  ('valorVar -> NUMBER','valorVar',1,'p_valorVar','parser.py',20),
  ('valorVar -> DOUBLE','valorVar',1,'p_valorVar','parser.py',21),
  ('valorVar -> CADENA','valorVar',1,'p_valorVar','parser.py',22),
  ('expresionVar -> valorVar','expresionVar',1,'p_expresionVar','parser.py',25),
  ('expresionVar -> ID','expresionVar',1,'p_expresionVar','parser.py',26),
  ('expresionVar -> expresionVar operadorA expresionVar','expresionVar',3,'p_expresionVar','parser.py',27),
  ('expresionBool -> VARBOOL ID EQUALS booleano pto_coma','expresionBool',5,'p_expresionBool','parser.py',31),
  ('expresionBool -> VAR ID EQUALS booleano pto_coma','expresionBool',5,'p_expresionBool','parser.py',32),
  ('booleano -> TRUE','booleano',1,'p_booleano','parser.py',35),
  ('booleano -> FALSE','booleano',1,'p_booleano','parser.py',36),
  ('lista -> expLista','lista',1,'p_lista','parser.py',41),
  ('lista -> add_lista','lista',1,'p_lista','parser.py',42),
  ('expLista -> VAR ID EQUALS NEW LISTA LPAREN NUMBER RPAREN pto_coma','expLista',9,'p_expLista','parser.py',46),
  ('expLista -> VAR ID EQUALS NEW LISTA LPAREN RPAREN pto_coma','expLista',8,'p_expLista','parser.py',47),
  ('expLista -> VAR ID EQUALS LCORCHETE elementosLista RCORCHETE pto_coma','expLista',7,'p_expLista','parser.py',48),
  ('add_lista -> ID LCORCHETE NUMBER RCORCHETE EQUALS num_cadena pto_coma','add_lista',7,'p_add_lista','parser.py',53),
  ('add_lista -> ID PTO ADD LPAREN num_cadena RPAREN pto_coma','add_lista',7,'p_add_lista','parser.py',54),
  ('num_cadena -> NUMBER','num_cadena',1,'p_num_cadena','parser.py',58),
  ('num_cadena -> CADENA','num_cadena',1,'p_num_cadena','parser.py',59),
  ('elementosLista -> CADENA','elementosLista',1,'p_elementosLista','parser.py',63),
  ('elementosLista -> NUMBER','elementosLista',1,'p_elementosLista','parser.py',64),
  ('elementosLista -> CADENA COMA elementosLista','elementosLista',3,'p_elementosLista','parser.py',65),
  ('elementosLista -> NUMBER COMA elementosLista','elementosLista',3,'p_elementosLista','parser.py',66),
  ('elementosLista -> <empty>','elementosLista',0,'p_elementosLista','parser.py',67),
  ('mapa -> expMapa','mapa',1,'p_mapa','parser.py',71),
  ('mapa -> add_mapa','mapa',1,'p_mapa','parser.py',72),
  ('expMapa -> VAR ID EQUALS NEW MAPA LPAREN RPAREN pto_coma','expMapa',8,'p_expMapa','parser.py',76),
  ('expMapa -> MAPA ID EQUALS LCURLYB elementosMapa RCURLYB pto_coma','expMapa',7,'p_expMapa','parser.py',77),
  ('elementosMapa -> num_cadena DOSPTO num_cadena','elementosMapa',3,'p_elementosMapa','parser.py',82),
  ('elementosMapa -> num_cadena DOSPTO num_cadena COMA elementosMapa','elementosMapa',5,'p_elementosMapa','parser.py',83),
  ('add_mapa -> ID LCORCHETE CADENA RCORCHETE EQUALS CADENA pto_coma','add_mapa',7,'p_add_mapa','parser.py',88),
  ('operadorA -> PLUS','operadorA',1,'p_operadorA','parser.py',92),
  ('operadorA -> MINUS','operadorA',1,'p_operadorA','parser.py',93),
  ('operadorA -> TIMES','operadorA',1,'p_operadorA','parser.py',94),
  ('operadorA -> DIVIDE','operadorA',1,'p_operadorA','parser.py',95),
  ('operadorA -> DIVIDE_E','operadorA',1,'p_operadorA','parser.py',96),
  ('incremento -> ID INCREMENTO pto_coma','incremento',3,'p_incremento','parser.py',100),
  ('decremento -> ID DECREMENTO pto_coma','decremento',3,'p_decremento','parser.py',103),
  ('concatenacion -> VAR ID EQUALS ID PTO SUBSTRING LPAREN NUMBER COMA NUMBER RPAREN pto_coma','concatenacion',12,'p_concatenacion','parser.py',108),
  ('pto_coma -> PUNTCOM','pto_coma',1,'p_pto_coma','parser.py',123),
]
